### ISSUE TITLE
Suggestion: only display when off/on.

### ISSUE THREAD

**Issue by poi56iop** [lostcoastwizard/skull-prevention-reminder#1]
Some users only care when their setting is not whatever it usually is; maybe add a combobox option asking 'hide [never/when on/when off]'

E.g.: On an Iron I basically always want skull prevention off; unless skulling for revs; and there is a risk of forgetting to re-enable the option.

Thanks!

**Comment by lostcoastwizard** [comment]
A new configuration option has been added.
![Screenshot 2024-10-22 112103](https://github.com/user-attachments/assets/dc43c2b9-c667-4d6c-94ad-360451f55065)

**Comment by lostcoastwizard** [comment]
The status of the update can be viewed at https://github.com/runelite/plugin-hub/pull/6847
